### ISSUE TITLE
El puntaje por reglas recuerda el momento en el que tuve más reglas

### ISSUE THREAD

**Issue by benotti** [lvklabs/chatbot#13]
El puntaje por reglas deberia corresponder siempre al puntaje que tengo al momento actual, o al momento de submitir, sino alquien puede haber acumulado mucho puntaje y luego eliminar todas las reglas. Nunca nos enterarmos qué reglas definio ni porque junto tantos puntos.

**Comment by paglian** [comment]
Encontrado en v1.0
Arreglado en v1.1
