### ISSUE TITLE
El guardar como no funciona

### ISSUE THREAD

**Issue by benotti** [lvklabs/chatbot#17]
El guardar cambia el nombre del chatbot actual durante la sesion y parece funcionar. Sin embargo, no creo el archivo con el nuevo nombre sino que sigue guardando los cambios en el chatbot anterior.

**Comment by paglian** [comment]
Encontrado en v1.0
Arreglado en v1.1

**Comment by benotti** [comment]
No seria mejor que la proxima version sea la 1.01 o 1.05. Quizás
necesitemos mas de 9 ...

On Thu, Oct 18, 2012 at 2:26 PM, Andres Pagliano
notifications@github.comwrote:

> Encontrado en v1.0
> Arreglado en v1.1
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lvklabs/chatbot/issues/17#issuecomment-9573067.

## 

Prof. Dr. Luciana Benotti
FaMAF, Universidad Nacional de Cordoba
Medina Allende s/n
5000 Cordoba, Argentina
+54-351-5353701 (Int. 41414 or 43030)
http://cs.famaf.unc.edu.ar/~luciana
benotti@famaf.unc.edu.ar
