### ISSUE TITLE
Problema de visualizacion del nombre de la solapa enseñar reglas

### ISSUE THREAD

**Issue by benotti** [lvklabs/chatbot#18]
Este problema de interfaz fue observado en Ubuntu 10.04. Screenshot en: 
https://docs.google.com/open?id=0B4ZIXPp5qNrINmFVclNFQ1RXZ0E

**Comment by paglian** [comment]
No lo puedo reproducir. Podrías darme un secuencia de pasos para reproducirlo?

**Comment by benotti** [comment]
Yo tampoco lo puedo reproducir, pense que me pasaba todo el tiempo pero no
es asi. Cuando lo pueda reproducir te aviso.

On Thu, Oct 18, 2012 at 4:15 PM, Andres Pagliano
notifications@github.comwrote:

> No lo puedo reproducir. Podrías darme un secuencia de pasos para
> reproducirlo?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lvklabs/chatbot/issues/18#issuecomment-9578519.

## 

Prof. Dr. Luciana Benotti
FaMAF, Universidad Nacional de Cordoba
Medina Allende s/n
5000 Cordoba, Argentina
+54-351-5353701 (Int. 41414 or 43030)
http://cs.famaf.unc.edu.ar/~luciana
benotti@famaf.unc.edu.ar

**Comment by paglian** [comment]
Lo pude reproducir lanzando la aplicación cuando el SO se encuentra con pocos recursos (mucha carga de CPU y poca RAM)

**Comment by paglian** [comment]
Arreglado en v1.4
