### ISSUE TITLE
Otra interacción incorrecta entre asteriscos y variables

### ISSUE THREAD

**Issue by benotti** [lvklabs/chatbot#21]
A la hora de poner el asterisco con una variable cerca como:
Te gusto la pelicula de [variable] rodrigues *

La frase: Te gusto la pelicula de pancho rodrigues
no matchea. 

Este bug fue reportado por un participante de Dale Aceptar en el foro:
http://www.daleaceptar.gob.ar/forum/topic/998/

**Comment by paglian** [comment]
Duplicado. Si bien el orden de \* y [] están invertidos, es el mismo error que https://github.com/lvklabs/chatbot/issues/7
