### ISSUE TITLE
Conjugación sabia, no matchea si no es con acento.

### ISSUE THREAD

**Issue by Emilia-Echeveste14** [lvklabs/chatbot#23]
De la conjugación de saber, sabia sin acento no matchea.
Regla:
Si el usuario escribe:
 _saber_

Chatbot responde:
 Yo se que en Cordoba, en la cuidad universitaria, esta FaMAF. Ahi se estudia la licenciatura en computacion.

Por ejemplo, si escribo:

User: No, no sabia.
Chatbot: responde con la evasiva.

Pero si escribo:
User: No, no sabía. (poniendole acento)
Chatbot: responde correctamente.

**Comment by paglian** [comment]
Es el mismo error que https://github.com/lvklabs/chatbot/issues/9. Lo cierro como duplicado
