### ISSUE TITLE
Topics que no se mantienen

### ISSUE THREAD

**Issue by benotti** [lvklabs/chatbot#27]
Los topics no se mantienen de la manera esperada. Para reproducir el comportamiento no deseado cargar el chatbot disponible en https://docs.google.com/file/d/0B4ZIXPp5qNrITHhHMjJlbHpReVk/edit

y despues tener la conversacion: 

Yo: uy me olvide
Chatbot: Como no te vas a acordar de mi cumple??? Ahora pensaré si te invito a mi fiesta :P jaja

en este punto el chatbot deberia haber entrado a la categoria "Olvidos de cumpleaños" por lo cual al decirle:

Yo: bueno ... feliz cumpleaños

se espera que matchee con la regla que coincide y que está en la misma categoría: 

Si el usuario escribe:
- feliz cumpleaños \* 
- feliz cumple *
  Chatbot responde:
  Tarde! jaja Pero lo que vale es que me lo hayas dicho!! :P

Pero matchea con una regla de la categoria "deseos":

Si el usuario escribe:
 _pases_
- que tengas *
  _termines_
  _Buen_
  _salga_
  Chatbot responde:
  Ah! Gracias, de verdad!! Me gusta mucho lo que decis! Espero verte esta noche en mi fiesta!
  Gracias, te espero en mi casa para comer torta! ;)

**Comment by paglian** [comment]
Actualmente el engine no mantiene la categoría de manera estricta, es decir, si encuentra una regla que "matchea mejor" en otra categoría se cambia de categoría. Este comportamiento se podría cambiar para que sea mas estricto. Si bien haría que sea mas predecible no estoy seguro de que mejore los resultados dado que siempre se quedaría en la categoría actual convirtiéndolo en monotemático.

Concretamente, dado el input "bueno ... feliz cumpleaños". Para el AIML, la regla:

\* buen \* (en la categoría "Deseos")

es más específica o mejor candidata que

 * feliz cumpleaños \*  (en la categoría "Olvidos")

Notar que el input lematizado se transforma en "buen feliz cumpleaños". 

Voy a investigar si puedo lograr el comportamiento esperado

**Comment by paglian** [comment]
Con unos cambios menores en nuestra lib de AIML se puede hacer. El comportamiento quedaría de la siguiente manera:

Si hay match en la categoría actual elije esa regla (aunque exista una mejor "candidata" en otra categoría). 
Si no hay match en la categoría actual busca en las categorías restantes. 

Notar que si definimos una regla que matchea todo, por ejemplo:

*

Al momento en que entramos en la categoría que contiene dicha regla no podemos salir mas, convirtiendo nuestro chatbot en monotemático.

**Comment by paglian** [comment]
Arreglado en v1.4
