### ISSUE TITLE
"Abrir último" aparece en el menú de inicio cuando no debe

### ISSUE THREAD

**Issue by benotti** [lvklabs/chatbot#3]
"Abrir último" aparece en el menú de inicio cuando no aún no se creo ningún chatbot. Al intentar seleccionar esta opción da un error: "No se pudo abrir /home/luciana/Projects/Chatbot/builds/chatbot-linux32-0.09/mychatbot.crf". Al aceptar este error (unica opcion disponible) se abre la pantalla vieja de inicio (con los íconos sobre una pantalla vacía, sin el fondo creado por el diseñador). 

Esto ocurre cuando ejecuto el chatbot desde la ubicación: /home/luciana/Desktop/chatbot-linux32-0.27. Cómo está implementado el abrir último? Busca archivos crf en todo el disco? 

Version 0.27 - linux

**Comment by paglian** [comment]
Este error se debe a que hubo versiones viejas instaladas que dejaron keys inválidas de configuración. No debería ocurrir en máquinas "limpias" que no usaron versiones de desarrollo.
