### ISSUE TITLE
Compilación en Windows

### ISSUE THREAD

**Issue by mvanotti** [lvklabs/chatbot#40]
Hola!

Estoy tratando de compilar el programa en windows, pero no me queda del todo claro cuál es el entorno necesario para armar el proyecto.

Me instalé Qt4 y MinGW, y traté de compilarlo con eso, sin embargo, en release.sh parece decir que se necesita cygwin. Salteando eso y compilando igual, obtengo un binario que no se puede ejecutar, pues tira un Access Violation (¿tal vez por alguna de las third party libs?)

Usando cygwin, en principio no compilaba bien, porque el qmake me creaba los makefiles con paths que no eran soportados por el make de cygwin (c:/ ponía), reemplazando eso a mano, en el proceso final de linkeo se rompía, porque el ld de cygwin no reconocía el flag -lmingw32 que le ponía solo.

Luego probé instalando los paquetes de Qt4 en cygwin, y parece que por algún motivo la compilación lo detecta como linux, porque linkea contra las libs -lpcre en lugar de -lpcre_win32 y cosas así. Cambiandolas a mano, pareciera que la versión de libstdc++ que uso (la que viene con cygwin), no es compatible con la que se usó para buildear las third_party_libs

**Comment by paglian** [comment]
Hola, si el entorno es Qt4 + MinGW + Cygwin.

Sin tener el output exacto de los errores que tuviste es dificil saber exactamente cual es el problema. Todo indicaría que la versión de MinGW que estás usando no es compatible. Las librerías precompiladas estan para facilitar la compilación del proyecto pero si la versión de MinGW que estas usando no es compatible con la versión que fue usada, entonces vas a tener que compilar todas las dependencias. Compilar Freeling 2.2 en windows no es trivial, las que están distribuidas en el repositorio fueron compiladas haciendo cross-compiling desde Linux.

Para darte mas información necesito saber exactamente cuales son los errores que tuviste y que versiones estás usando. De nuevo, todo indicaría que estas mesclando librerias incompatibles.

**Comment by mvanotti** [comment]
Hola, muchas gracias por responder

Estoy usando Qt 4.8.6 (el último Qt4 que está en la web de Qt), y en cygwin instalé los paquetes con el manager de https://cygwin.com/install.html

Lo que hago es: Abro la consola de cygwin y ejecuto ./release.sh

Este es el comando con el que falla y su output.
http://pastebin.com/e6zh9deW
Si te fijas, está linkeando contra las librerias de linux y no las de windows (_win32) me parece que ahí el qmake-qt4 piensa que corre en linux.

Cuando agrego los _win32, y lo ejecuto de nuevo, me tira esto:
http://pastebin.com/NnX2JfJW

Pareciera ser que el problema ahora está en que la versión de libstdc++ no es compatible con la de las librerias estas.

¿Cómo hacen ustedes para buildear? ¿lo hacen desde cygwin o desde msys? ¿tienen los paquetes de qt4 instalados desde cygwin o usan el qt4 para windows con mingw?

Pensé en builder las libs, pero como decís vos, Freeling parece complicado, buscando en internet noté que decía que no tenía soporte para windows :(

**Comment by paglian** [comment]
Si, desde Cygwin (es un script de Bash)
Qt4 para Windows con MinGW

Si se está confundiendo de plataforma. Probá lo siguiente: Editá el script release.sh y borrá el if...then de manera que siempre inicialice:
target_os=win32
pkg_format=zip

De esta manera estamos seguros de que el script se ejecuta como debería. Capaz que ya estás haciendo esto. Si el error de linkeo persiste entonces alguna de las librerías de tu sistema no son compatibles con las versiones precompiladas.

TIP: Si el linker no puede encontrar ciertas funciones, averigua a que librerías pertenecen esas funciones, ahi podés identificar si te está faltando linkear algo o si son incompatibles

**Comment by paglian** [comment]
15 días sin respuesta. Cerrado por inactividad.
