### ISSUE TITLE
Interacción incorrecta entre asteriscos y variables

### ISSUE THREAD

**Issue by benotti** [lvklabs/chatbot#7]
La regla con el estimulo: \* tengo miedo a [frase]
y la respuesta: desde cuándo le tenés miedo a [frase]?

funciona de este manera:

amigo: le tengo miedo a los aviones
chatbot: desde cuándo le tenés miedo a le?
amigo: yo tengo miedo a las arañas
chatbot: desde cuándo le tenés miedo a yo?

Probablemente está poniendo las palabras que matchean con el asterisco en la variable [frase]

**Comment by paglian** [comment]
> Probablemente está poniendo las palabras que matchean con el asterisco en la variable [frase]

Si es exactamente lo que pasa debido a una limitación en nuestra lib de AIML. Esta es una "known issue", ver trello #12.

**Comment by paglian** [comment]
Arreglado en v2.0
